# Generated by Django 4.0.2 on 2022-02-04 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='search',
            old_name='input',
            new_name='search',
        ),
    ]
